### ISSUE TITLE
Cursor does not track on line edits

### ISSUE THREAD

**Issue by kmatt** [filimonov/chc#6]
Running 0.1.5 on macOS High Sierra in both Terminal.app and iTerm2 with -m and editing a query after recalling it with the up-arrow, sometimes the cursor does not track the edit position, often lagging one space to the right. 

It appears to occur when the SQL wraps in the terminal window. Changed characters then are inserted visually one space off, only visible when the query is run, and the error contains the actual SQL.

Reproduce:

1) Run a query that wraps to a second terminal line
2) Up-arrow to recall it
3) Left arrow into the SQL
4) Press delete key

**Comment by filimonov** [comment]
Tganks, i'll check it.

Sounds quite similar to https://github.com/peterh/liner/issues/98

**Comment by filimonov** [comment]
@kmatt can you check https://github.com/filimonov/chc/releases/tag/v0.1.6? 

Currently I have no macOS station (will be able to test only at the end of next week), but on Windows the cursor is tracked properly after that fix.

**Comment by filimonov** [comment]
It introduce another problems (at the bottom of the screen on Windows). :\

**Comment by filimonov** [comment]
Fixed in v0.1.6. Also in upstream project (https://github.com/peterh/liner/issues/98).
